### ISSUE TITLE
Fix 20 Question Game State from crashing setup when installed

### ISSUE THREAD

**Issue by Aevyz** [Roboy/DialogSystem#72]
Specifically this line appears not to work w/o Internet and crashes the whole setup. 

```
private Akiwrapper aw = new AkiwrapperBuilder().setFilterProfanity(true).build();
```

This leads to:

```
Exception in thread "main" java.lang.RuntimeException: State with identifier GamingTwentyQuestionsState is missing!
	at roboy.dialog.DialogStateMachine.parseAndSetTransitionsAndFallbacks(DialogStateMachine.java:392)
	at roboy.dialog.DialogStateMachine.loadFromJSON(DialogStateMachine.java:315)
	at roboy.dialog.DialogStateMachine.loadFromFile(DialogStateMachine.java:262)
	at roboy.dialog.Conversation.<init>(Conversation.java:61)
	at roboy.dialog.ConversationManager.createConversation(ConversationManager.java:222)
	at roboy.dialog.ConversationManager.main(ConversationManager.java:118)
```

### Things to Fix:

- [x] ~~Launching State Exception~~ No need for exception due to refactor
- [x] ~~Optional: If connection lost, quit game~~ Not possible

**Comment by Aevyz** [comment]
Fixed in #85

**Comment by markozajc** [comment]
Akiwrapper is a REST API wrapper library (thanks for using it by the way!) that requires internet connection to communicate with Akinator's servers, which can't be accessed without Internet access. Building a new instance of Akiwrapper also creates a new game session, which may throw an exception in that case.
